apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: pvc-sample
  name: pvc-sample-storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-storagecluster-ceph-rbd
  volumeMode: Filesystem
